
name: Run tests for pull requests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./webappBackend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ${{env.working-directory}}
    - run: npm run start
      working-directory: ${{env.working-directory}}
    - run: npm run test
      working-directory: ${{env.working-directory}}
      env:
        CI: true
